---

- name: OPNSense Control Center - Setup
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  module_defaults:
    ansible.builtin.setup:
      gather_subset: ['!all', 'os_family', 'all_ipv4_addresses']

  vars:
    OPNCC_MANAGE:
      nftables: true
      logserver: true  # graylog/mongodb/opensearch stack

    OPNCC_VARS:
      domain: ''
      aliases: []
      mail_domain: ''
      admin_mail: ''

      port:
        http: 80
        https: 443
        ssh: 22
        firewalls: [443, 22]  # ports that are in use for firewall http+s
        gogs:
          web: 8001
          git: 2222
        graylog:
          web: 8002
          syslog: 5514
          opensearch:
            api: 9200
            perf: 9600
        ide: 8003
        semaphore: 8004

      networks:
        # todo: check any src works if unset/empty
        allow_web: ['192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8']
        allow_ssh: ['192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8']
        deny: []
        docker: '192.168.69.0/24'
        docker_default: '192.168.69.240/28'
      url:
        default: 'ide'
        ansible: 'ans'
        logserver: 'log'
        ide: 'ide'
        vcs: 'vcs'

    OPNCC_VERSIONS:
      gogs: 'latest'  # vcs
      logserver:
        graylog: '5.0'
        graylog_min: '5.0.7'
        mongodb: '5.0.17'
        opensearch: 'latest'
      codeserver: 'latest'  # web-ide
      semaphore: 'latest'  # ansible web-ui

  pre_tasks:
    - name: Pre-Check | Domain is set and valid
      ansible.builtin.assert:
        that:
          - OPNCC_VARS.domain | default(none, true) is not none
          - OPNCC_VARS.domain | valid_hostname

    - name: Pre-Check | Comparing active SSH port with configured one
      ansible.builtin.shell: |
        set -o pipefail
        lsof -i -P -n | grep LISTEN | grep ssh
      register: pc_ssh
      failed_when: >
        pc_ssh.failed or
        ':' + OPNCC_VARS.port.ssh | string not in pc_ssh.stdout
      args:
        executable: '/bin/bash'
      changed_when: false
      when: OPNCC_MANAGE.nftables | bool

  roles:
    - role: nftables
      when: OPNCC_MANAGE.nftables | bool
      tags: [nftables, setup]

    - role: ansibleguy.infra_docker_minimal
      vars:
        docker:
          compose:
            enable: true
            version: '2.18.0'
          nftables:
            bridge_none: false  # build-process
            disable_iptables: true
            reload: true
          address_pool: "base={{ OPNCC_VARS.networks.docker_default }},size=28"
      tags: [docker, setup]

    - role: nginx
      tags: [nginx, setup, services]

    - role: setup
      tags: [setup, services]
