---

- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  module_defaults:
    ansible.builtin.setup:
      gather_subset: ['!all', 'os_family']

  vars:
    OPNCC_MANAGE:
      nftables: true
      logserver: true  # graylog/mongodb/opensearch stack

    OPNCC_VARS:
      domain: ''
      mail_domain: ''
      admin_mail: ''

      port:
        http: 80
        https: 443
        ssh: 22
        firewalls: [443, 22]  # ports that are in use for firewall http+s
      networks:
        # todo: check any src works if unset/empty
        allow_web: ['192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8']
        allow_ssh: ['192.168.0.0/16', '172.16.0.0/12', '10.0.0.0/8']
        deny: []
        docker: '192.168.69.0/24'
        docker_default: '192.168.69.240/28'

    OPNCC_VERSIONS:
      gitea: 'latest'  # vcs
      logserver:
        graylog: '5.0'
        graylog_min: '5.0.7'
        mongodb: '5.0.17'
        opensearch: 'latest'
      codeserver: 'latest'  # web-ide
      semaphore: 'latest'  # ansible web-ui

  pre_tasks:
    - name: Pre-Check | Domain is set and valid
      ansible.builtin.assert:
        that:
          - OPNCC_VARS.domain | default(none, true) is not none
          - OPNCC_VARS.domain | valid_hostname

    - name: Pre-Check | Comparing active SSH port with configured one
      ansible.builtin.shell: 'lsof -i -P -n | grep LISTEN | grep ssh'
      register: pc_ssh
      failed_when: >
        pc_ssh.failed or
        ':' + OPNCC_VARS.port.ssh | string not in pc_ssh.stdout
      changed_when: false
      when: OPNCC_MANAGE.nftables | bool

  roles:
    - name: nftables
      when: OPNCC_MANAGE.nftables | bool
      tags: [nftables, setup]

    - name: ansibleguy.infra_docker_minimal
      vars:
        docker:
          compose:
            enable: true
            version: '2.18.0'
          nftables:
            bridge_none: false  # build-process
            disable_iptables: true
            reload: true
          address_pool: "base={{ OPNCC_VARS.networks.docker_default }},size=28"
      tags: [docker, setup]

    # NOTE: config just for testing purposes for now
    - name: ansibleguy.infra_nginx
      vars:
        nginx:
          sites:
            opncc_vcs:
              domain: 'vcs.opncc'
              aliases: ['vcs.opncc.localhost']
              mode: 'proxy'
              proxy:
                port: 8001
              security:
                restrict_methods: false
            opncc_log:
              domain: 'log.opncc'
              aliases: ['log.opncc.localhost']
              mode: 'proxy'
              proxy:
                port: 8002
              security:
                restrict_methods: false
            opncc_ide:
              domain: 'ide.opncc'
              aliases: ['ide.opncc.localhost']
              mode: 'proxy'
              proxy:
                port: 8004
              security:
                restrict_methods: false
            opncc_ans:
              domain: 'ans.opncc'
              aliases: ['ans.opncc.localhost']
              mode: 'proxy'
              proxy:
                port: 8005
              security:
                restrict_methods: false
      tags: [nginx, setup, services]

    - setup
