---

- name: OPN-CC | Docker & Network settings
  ansible.builtin.import_tasks: network_docker.yml

- name: OPN-CC | Installing Git
  ansible.builtin.apt:
    name: 'git'
    state: present

- name: OPN-CC | Installing Python3-Pip
  ansible.builtin.apt:
    name: 'python3-pip'
    state: present

- name: OPN-CC | Configure log forwarding
  ansible.builtin.template:
    src: 'templates/etc/rsyslog.d/10-logserver.conf.j2'
    dest: '/etc/rsyslog.d/10-logserver.conf'
    mode: 0644
  notify: Restart-rsyslog

- name: OPN-CC | Creating directories
  ansible.builtin.file:
    path: "{{ item.p }}"
    state: directory
    mode: "{{ item.m | default('0750') }}"
    owner: "{{ item.o }}"
    group: "{{ item.g | default(item.o) }}"
  with_items:
    # base
    - {p: "{{ OPNCC_PATH_BASE.config }}", o: "{{ OPNCC_USER }}", m: '0755'}
    - {p: "{{ OPNCC_PATH_BASE.lib }}", o: "{{ OPNCC_USER }}", m: '0755'}
    - {p: "{{ OPNCC.path.config.compose }}", o: "{{ OPNCC_USER }}"}
    # vcs
    - {p: "{{ OPNCC.path.data.gogs }}", o: "{{ OPNCC.users.gogs }}", m: '0755'}
    - {p: "{{ OPNCC.path.config.gogs }}", o: "{{ OPNCC.users.gogs }}"}
    - {p: "{{ OPNCC.path.backup.gogs }}", o: "{{ OPNCC.users.gogs }}"}
    # logserver
    - {p: "{{ OPNCC.path.config.graylog }}", o: "{{ OPNCC.users.graylog }}", g: "{{ OPNCC_USER }}"}
    - {p: "{{ OPNCC.path.data.graylog }}", o: "{{ OPNCC.users.graylog }}"}
    - {p: "{{ OPNCC.path.data.mongodb }}", o: "{{ OPNCC.users.mongodb }}"}
    - {p: "{{ OPNCC.path.data.opensearch }}", o: "{{ OPNCC.users.opensearch }}"}
    - {p: "{{ OPNCC.path.config.compose }}/build_opensearch", o: 'root', g: "{{ OPNCC_USER }}"}
    - {p: "{{ OPNCC.path.config.compose }}/build_graylog", o: 'root', g: "{{ OPNCC_USER }}"}
    # ide
    - {p: "{{ OPNCC.path.data.ide }}", o: "{{ OPNCC.users.ide }}"}
    - {p: "{{ OPNCC.path.data.ide }}/main", o: "{{ OPNCC.users.ide }}"}
    - {p: "{{ OPNCC.path.config.ide }}", o: "{{ OPNCC.users.ide }}"}
    - {p: "{{ OPNCC.path.config.ide }}/code-server", o: "{{ OPNCC.users.ide }}"}
    # ansible
    - {p: "{{ OPNCC.path.data.ansible }}", o: "{{ OPNCC.users.semaphore }}", g: "{{ OPNCC.users.ide }}", m: '0770'}
    - {p: "{{ OPNCC.path.data.semaphore }}", o: "{{ OPNCC.users.semaphore }}"}
    - {p: "{{ OPNCC.path.data.semaphore }}/db", o: "{{ OPNCC.users.semaphore }}"}
    - {p: "{{ OPNCC.path.data.semaphore }}/run", o: "{{ OPNCC.users.semaphore }}"}
    - {p: "{{ OPNCC.path.data.semaphore }}/.ssh", o: "{{ OPNCC.users.semaphore }}"}
    - {p: "{{ OPNCC.path.config.semaphore }}", o: "{{ OPNCC.users.semaphore }}"}
    - {p: "{{ OPNCC.path.config.compose }}/build_semaphore", o: 'root', g: "{{ OPNCC_USER }}"}
    # web
    - {p: "{{ OPNCC.path.data.web }}", o: 'root', g: 'www-data'}
    - {p: "{{ OPNCC.path.data.auth }}", o: 'root', g: "{{ OPNCC.users.auth }}", m: '0770'}
    - {p: "{{ OPNCC.path.data.auth }}/templates", o: 'root', g: "{{ OPNCC.users.auth }}"}
    - {p: "{{ OPNCC.path.data.auth }}/venv", o: 'root', g: "{{ OPNCC.users.auth }}"}
