---

- name: OPN-CC | Users
  ansible.builtin.import_tasks: users.yml
  when: setup_part == 1

- name: OPN-CC | Base
  ansible.builtin.import_tasks: base.yml
  when: setup_part == 1

- name: OPN-CC | Processing services
  ansible.builtin.import_role:
    name: services
  when: setup_part == 2
