---

- name: OPN-CC | Network | Configuring sysctl to allow traffic forwarding
  ansible.posix.sysctl:
    name: 'net.ipv4.ip_forward'
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: OPN-CC | Docker | Installing IPTables to use with docker-compose
  ansible.builtin.apt:
    name: 'iptables'
    state: present

- name: OPN-CC | Docker | Allowing service-user to run docker-compose
  ansible.builtin.user:
    name: "{{ OPNCC_USER }}"
    groups: 'docker'
    append: true

- name: OPN-CC | Docker | Allowing service-user to reload NFTables (to flush unwanted docker IPTables rules)
  ansible.builtin.copy:
    content: |
      # ansible_managed
      {{ OPNCC_USER }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl reload nftables.service
    dest: "/etc/sudoers.d/opncc"
    validate: '/usr/sbin/visudo -cf %s'
    mode: 0640
    owner: 'root'
    group: 'root'
  when: OPNCC_MANAGE.nftables | bool
