---

- name: OPN-CC | Services | Build | Download Container Build-Files
  ansible.builtin.unarchive:
    src: "{{ item.u }}"
    remote_src: true
    dest: "{{ OPNCC.path.config.compose }}/build_{{ item.n }}/"
    mode: 0750
    owner: 'root'
    group: "{{ OPNCC_USER }}"
  with_items:
    - {n: 'opensearch', u: 'https://github.com/opensearch-project/docker-images/archive/refs/heads/main.zip'}
    - {n: 'graylog', u: "https://github.com/Graylog2/graylog-docker/archive/refs/heads/{{ OPNCC_VERSIONS.logserver.graylog }}.zip"}

# NOTE: build-process expects git repo..
- name: OPN-CC | Services | Build | Cloning Container Build-Files
  ansible.builtin.git:
    repo: "{{ item.r }}"
    dest: "{{ OPNCC.path.config.compose }}/build_{{ item.n }}/"
    version: "{{ item.v | default(omit) }}"
    depth: 1
    force: true  # if version-change
  with_items:
    - {n: 'semaphore', r: 'https://github.com/ansible-semaphore/semaphore.git', v: "v{{ OPN_VERSIONS_LATEST.semaphore }}"}

- name: OPN-CC | Services | Build | Patch Container Build-Files (UID/GID/VERSION)
  ansible.builtin.replace:
    path: "{{ OPNCC.path.config.compose }}/build_{{ item.p }}"
    regexp: "{{ item.s }}"
    replace: "{{ item.r }}"
  with_items:
    - {p: "graylog/graylog-docker-{{ OPNCC_VERSIONS.logserver.graylog }}/docker/oss/Dockerfile",
       s: 'COPY health_check\.sh \/\n\n',
       r: 'COPY health_check.sh /\nRUN chmod 775 /docker-entrypoint.sh\n\n'}
    - {p: 'semaphore/deployment/docker/prod/Dockerfile', s: ' 1001', r: " {{ OPNCC.users.semaphore }}"}
    - {p: 'semaphore/deployment/docker/prod/buildx.Dockerfile', s: ' 1001', r: " {{ OPNCC.users.semaphore }}"}
    - {p: 'semaphore/deployment/docker/prod/goss.yaml', s: 'uid: 1001', r: "uid: {{ OPNCC.users.semaphore }}"}
    - {p: 'semaphore/deployment/docker/prod/bin/install', s: ' 1001:', r: " {{ OPNCC.users.semaphore }}:"}

- name: OPN-CC | Services | Build | Dockerfiles
  ansible.builtin.template:
    src: "templates/etc/opn-cc/docker-compose/{{ item }}.j2"
    dest: "{{ OPNCC.path.config.compose }}/{{ item }}_dockerfile"
    mode: 0640
    owner: 'root'
    group: "{{ OPNCC_USER }}"
  loop:
    - 'logserver_mongodb'
