---

- name: OPN-CC | Services | App Configs
  ansible.builtin.template:
    src: "templates/etc/opn-cc/{{ item.f }}.j2"
    dest: "{{ OPNCC_PATH_BASE.config }}/{{ item.f }}"
    mode: 0640
    owner: "{{ item.o }}"
    group: "{{ item.g | default(item.o) }}"
  with_items:
    - {f: 'vcs/gitea/app.ini', o: "{{ OPNCC.users.gitea }}"}
    - {f: 'logserver/graylog/log4j2.xml', o: "{{ OPNCC.users.graylog }}"}
    - {f: 'ide/config.yaml', o: "{{ OPNCC.users.ide }}"}
    - {f: 'logserver/graylog/graylog.conf', o: "{{ OPNCC.users.graylog }}", m: '0400'}
    - {f: 'ansible/semaphore/config.json', o: "{{ OPNCC.users.semaphore }}", m: '0400'}

- name: OPN-CC | Services | One-Time App Configs
  ansible.builtin.include_tasks: config_onetime.yml
  loop_control:
    loop_var: _config
  with_items: []

- name: OPN-CC | Services | Build Containers
  ansible.builtin.import_tasks: build.yml
  tags: build

- name: OPN-CC | Services | Docker-compose configs
  ansible.builtin.template:
    src: "templates/etc/opn-cc/docker-compose/{{ item }}.yml.j2"
    dest: "{{ OPNCC.path.config.compose }}/{{ item }}.yml"
    mode: 0640
    owner: 'root'
    group: "{{ OPNCC_USER }}"
  loop:
    - 'vcs'
    - 'logserver'
    - 'ide'
    - 'ansible'

- name: OPN-CC | Services | Docker-compose services
  ansible.builtin.template:
    src: "templates/etc/systemd/system/{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: 0644
    owner: 'root'
    group: 'root'
  loop:
    - 'opn-cc-vcs'  # gitea
    - 'opn-cc-log'  # logserver/graylog
    - 'opn-cc-ide'  # code-server
    - 'opn-cc-ansible'  # ansible/semaphore

- name: OPN-CC | Services | Enabling services
  ansible.builtin.systemd:
    name: "{{ item }}.service"
    enabled: true
    daemon_reload: true
  loop:
    - 'opn-cc-vcs'
    - 'opn-cc-log'
    - 'opn-cc-ide'
    - 'opn-cc-ansible'
