---

- name: OPN-CC | Nginx | Auth | Copying public web-files
  ansible.builtin.template:
    src: "templates/var/local/lib/opn-cc/web/{{ item }}.j2"
    dest: "{{ OPNCC.path.data.web }}/{{ item }}"
    mode: 0640
    owner: 'root'
    group: 'www-data'
  loop:
    - '401.html'

- name: OPN-CC | Nginx | Auth | Copying Authentication-service files
  ansible.builtin.template:
    src: "templates/var/local/lib/opn-cc/auth/{{ item }}.j2"
    dest: "{{ OPNCC.path.data.auth }}/{{ item }}"
    mode: 0650
    owner: 'root'
    group: "{{ OPNCC.users.auth }}"
  notify: Restart-auth
  loop:
    - 'main.py'
    - 'ldap.py'
    - 'totp.py'
    - 'file.py'
    - 'system.py'
    - 'templates/login.html'

- name: OPN-CC | Nginx | Auth | Installing python3-virtualenv
  ansible.builtin.pip:
    name: 'virtualenv'
    state: present

- name: OPN-CC | Nginx | Auth | Installing python3 modules into venv
  ansible.builtin.pip:
    name: ['flask', 'waitress', 'ldap3', 'python-pam']
    virtualenv: "{{ OPNCC.path.data.auth }}/venv"
    state: present
  notify: Restart-auth

- name: OPN-CC | Nginx | Auth | Session file
  ansible.builtin.file:
    state: touch
    access_time: preserve
    modification_time: preserve
    path: "{{ OPNCC.path.data.auth }}/sessions.txt"
    mode: 0600
    owner: "{{ OPNCC.users.auth }}"
    group: "{{ OPNCC.users.auth }}"

- name: OPN-CC | Nginx | Auth | Cron for session-cleanup
  ansible.builtin.cron:
    cron_file: 'opncc'
    name: 'OPNCC-AUTH Session Cleanup'
    minute: 0
    hour: '*'
    user: "{{ OPNCC.users.auth }}"
    job: "curl -i -XPOST http://127.0.0.1:{{ OPNCC_VARS.port.auth }}/{{ OPNCC_VARS.url.auth }}/cleanup"

- name: OPN-CC | Nginx | Auth | Authentication service
  ansible.builtin.template:
    src: "templates/etc/systemd/system/opn-cc-auth.service.j2"
    dest: "/etc/systemd/system/opn-cc-auth.service"
    mode: 0644
    owner: 'root'
    group: 'root'
  notify: Restart-auth

- name: OPN-CC | Nginx | Auth | Enabling & Starting service
  ansible.builtin.systemd:
    name: 'opn-cc-auth.service'
    enabled: true
    daemon_reload: true
    state: started
