---

OPNCC_VCS_ORG: 'opncc'

# if latest => pull current release from github
OPN_VERSIONS_LATEST:
  # gogs: "{{ 'gogs' | github_latest_release('gogs') if OPNCC_VERSIONS.gogs == 'latest' else OPNCC_VERSIONS.gogs }}"
  semaphore: "{{ 'ansible-semaphore' | github_latest_release('semaphore') if OPNCC_VERSIONS.semaphore == 'latest' else OPNCC_VERSIONS.semaphore }}"
  opensearch: "{{ 'opensearch-project' | github_latest_release('opensearch') if OPNCC_VERSIONS.logserver.opensearch == 'latest' else OPNCC_VERSIONS.logserver.opensearch }}"

OPNCC_IDE:
  root: '/home/coder/main'
  extensions:
    - 'redhat.ansible'
    - 'redhat.vscode-yaml'

OPNCC_SERVICES:
  - 'opn-cc-vcs'  # gogs
  - 'opn-cc-log'  # logserver/graylog
  - 'opn-cc-ide'  # code-server
  - 'opn-cc-ansible'  # ansible/semaphore
