---

- name: Restart-nginx
  ansible.builtin.systemd:
    name: 'nginx.service'
    state: restarted

- name: Restart-auth
  ansible.builtin.systemd:
    name: 'opn-cc-auth.service'
    state: restarted
