---

OPNCC_PATH_BASE:
  config: '/etc/opn-cc'
  lib: '/var/local/lib/opn-cc'

OPNCC_USER: 'opn-cc'

OPNCC:
  users:
    opn-cc: 1100  # used to run 'docker-compose'
    gitea: 1101
    graylog: 1102
    mongodb: 1103
    opensearch: 1104
    ide: 1105
    semaphore: 1106  # ansible

  port:
    gitea:
      web: 8001
      ssh: 2222
    graylog:
      web: 8002
      syslog: 5514
      opensearch:
        api: 9200
        perf: 9600
        dashboard: 8003
    ide: 8004
    semaphore: 8005

  path:
    data:
      gitea: "{{ OPNCC_PATH_BASE.lib }}/vcs/gitea"
      graylog: "{{ OPNCC_PATH_BASE.lib }}/logserver/graylog"
      mongodb: "{{ OPNCC_PATH_BASE.lib }}/logserver/mongodb"
      opensearch: "{{ OPNCC_PATH_BASE.lib }}/logserver/opensearch"
      ide: "{{ OPNCC_PATH_BASE.lib }}/ide"
      semaphore: "{{ OPNCC_PATH_BASE.lib }}/semaphore"
      ansible: "{{ OPNCC_PATH_BASE.lib }}/ansible"
    config:
      compose: "{{ OPNCC_PATH_BASE.config }}/docker-compose"
      gitea: "{{ OPNCC_PATH_BASE.config }}/vcs/gitea"
      graylog: "{{ OPNCC_PATH_BASE.config }}/logserver/graylog"
      ide: "{{ OPNCC_PATH_BASE.config }}/ide"
      semaphore: "{{ OPNCC_PATH_BASE.config }}/ansible/semaphore"
    bin:
      compose: '/usr/local/bin/docker-compose'

  network:
    vcs: '192.168.69.0/28'
    logserver: '192.168.69.16/28'
    ide: '192.168.69.32/28'
    ansible: '192.168.69.48/28'

  docker:
    extra_hosts:
      - "{{ OPNCC_DNS_HOST }}:host-gateway"
