---

OPNCC_PATH_BASE:
  config: '/etc/opn-cc'
  lib: '/var/local/lib/opn-cc'
  backup: '/var/backups/opn-cc'

OPNCC_USER: 'opn-cc'
OPNCC_DNS_HOST: 'opncc-host'
OPNCC_MAIL_BASE: "opn-cc@{{ OPNCC_VARS.mail_domain | default(OPNCC_VARS.domain, true) }}"

OPNCC:
  users:
    opn-cc: 1100  # used to run 'docker-compose'
    gogs: 1101
    graylog: 1102
    mongodb: 1103
    opensearch: 1104
    ide: 1105
    semaphore: 1106  # ansible
    auth: 1107

  path:
    data:
      gogs: "{{ OPNCC_PATH_BASE.lib }}/vcs/gogs"
      graylog: "{{ OPNCC_PATH_BASE.lib }}/logserver/graylog"
      mongodb: "{{ OPNCC_PATH_BASE.lib }}/logserver/mongodb"
      opensearch: "{{ OPNCC_PATH_BASE.lib }}/logserver/opensearch"
      ide: "{{ OPNCC_PATH_BASE.lib }}/ide"
      semaphore: "{{ OPNCC_PATH_BASE.lib }}/semaphore"
      ansible: "{{ OPNCC_PATH_BASE.lib }}/ansible"
      web: "{{ OPNCC_PATH_BASE.lib }}/web"
      auth: "{{ OPNCC_PATH_BASE.lib }}/auth"
    config:
      compose: "{{ OPNCC_PATH_BASE.config }}/docker-compose"
      gogs: "{{ OPNCC_PATH_BASE.config }}/vcs/gogs"
      graylog: "{{ OPNCC_PATH_BASE.config }}/logserver/graylog"
      ide: "{{ OPNCC_PATH_BASE.config }}/ide"
      semaphore: "{{ OPNCC_PATH_BASE.config }}/ansible/semaphore"
    bin:
      compose: '/usr/local/bin/docker-compose'
    backup:
      gogs: "{{ OPNCC_PATH_BASE.backup }}/vcs/gogs"

  network:
    vcs: "{{ OPNCC_VARS.networks.opncc_prefix }}.{{ OPNCC_VARS.networks.docker_prefix }}.0/28"
    logserver: "{{ OPNCC_VARS.networks.opncc_prefix }}.{{ OPNCC_VARS.networks.docker_prefix }}.16/28"
    ide: "{{ OPNCC_VARS.networks.opncc_prefix }}.{{ OPNCC_VARS.networks.docker_prefix }}.32/28"
    ansible: "{{ OPNCC_VARS.networks.opncc_prefix }}.{{ OPNCC_VARS.networks.docker_prefix }}.48/28"

  docker:
    extra_hosts:
      - "{{ OPNCC_DNS_HOST }}:host-gateway"
