---

name: AutoLint

on:
  push:
    branches: [dev, latest]
  pull_request:
    branches: [dev, latest]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.10]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
        shell: bash

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_lint.txt
        shell: bash

      - name: Running PyLint
        run: pylint --recursive=y .
        shell: bash

      - name: Running YamlLint
        run: yamllint .
        shell: bash

      - name: Preparing requirements for AnsibleLint
        run: |
          ansible-galaxy role install -r playbook/requirements.yml -p ./playbook/roles
          ansible-galaxy collection install -r requirements.yml -p ./playbook/collections
        shell: bash

      - name: Running AnsibleLint
        run: |
          cd playbook
          ansible-lint -c .ansible-lint.yml
        shell: bash
